### ISSUE TITLE
Ussage of HTTPS URLs only still requires ssh-agent

### ISSUE THREAD

**Issue by Bios-Marcel** [Southclaws/wadsworth#5]
Since write access is usually not required for most tasks, HTTPS URLs are quite enough. However, even though it all works fine via HTTPS, the git-client still requires a running SSH agent. While this is not a huge problem, it's quite annoying and it would be cool to to be able to use it without an SSH agent.

**Comment by Southclaws** [comment]
Yeah this would make sense. I never had a use case because HTTPS requires plaintext username+password or auth token for private repos and I always just preferred SSH for this use-case.

PR welcome, it should be just as simple as disabling the SSH if a user/pass is set or providing an env var to disable SSH.

**Comment by Bios-Marcel** [comment]
Well yeah, that's why i usually use SSH. But since in my case I do read only access on a public repository, it's totally fine. And I'd like to avoid spreading my SSH keys anyway.
